# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94bd057c3056df728a6bb7739dcc7cde30316e0fcba7e1bbed299c0e3c5ce4061d321ef4cebceb7fbde7845f50a6b58944271429ee64b45e5fcbc1f0358a040b

test:
  secret_key_base: eda5d4bf081971da0b883f4885d235083c517c80a1443ad1ec894feb0c8508ec54bb0f977fc27a811e9cf7c1ce243ddd8cf7982d5ba757cfe1a3b650841a8090

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
